# Site settings
title: Ben Alun-Jones
email: benalunjones@gmail.com
url: http://benalun-jones.github.io/
description: "Ben Alun-Jones's Junior Developer CV with added portfolio and skillset offerings"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Your Website

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SBootstrap
  # title: github
  #   url: https://github.com/IronSummitMedia/startbootstrap
  # title: linkedin
  #   url: https://uk.linkedin.com/in/benjamin-alun-jones-ab440499

# Build settings
markdown: kramdown
permalink: pretty
